basePath: '{{.BasePath}}'
definitions:
  models.GetPaysListOutputDto:
    properties:
      code:
        description: 业务状态代码
        example: 200
        type: integer
      data:
        description: 数据
        items:
          $ref: '#/definitions/models.PaymentInfoOutputDto'
        type: array
      error_detail:
        description: 详细错误
        example: 详细错误
        type: string
      msg:
        description: 信息
        example: 成功
        type: string
    type: object
  models.PaymentInfoInsertDto:
    properties:
      amount:
        description: 交易金额
        type: string
      pay_type:
        description: 支付方式
        type: string
      payer_email:
        description: 支付人邮箱
        type: string
      payer_message:
        description: 留言
        type: string
      payer_mobile_number:
        description: 支付人电话号码
        type: string
      payer_name:
        description: 支付人姓名
        type: string
    type: object
  models.PaymentInfoOutputDto:
    properties:
      amount:
        description: 交易金额
        type: string
      creation_date:
        description: 创建时间
        type: string
      id:
        description: 流水号
        type: integer
      pay_type:
        description: 支付方式
        type: string
      payee_email:
        description: 收款人邮箱
        type: string
      payee_mobile_number:
        description: 收款人电话号码
        type: string
      payee_name:
        description: 收款人姓名
        type: string
      payer_email:
        description: 支付人邮箱
        type: string
      payer_mobile_number:
        description: 支付人电话号码
        type: string
      payer_name:
        description: 支付人姓名
        type: string
      trading_status:
        description: 交易状态
        type: string
    type: object
  models.PrePaidOutputDto:
    properties:
      id:
        description: 流水号
        type: integer
      id_code:
        description: 支付票据号
        type: string
    type: object
  models.TradingStatusInputDto:
    properties:
      id:
        type: integer
      trading_status:
        type: string
    required:
    - id
    - trading_status
    type: object
host: '{{.Host}}'
info:
  contact:
    name: halower
    url: https://github.com/halower
  description: 个人点对点支付服务
  license:
    name: 源码协议
    url: https://github.com/halower/newbie-spring-boot-project/blob/master/license_996.txt
  title: 易支付
  version: "1.0"
paths:
  /api/pay/list:
    get:
      parameters:
      - description: 页码
        in: query
        name: page
        required: true
        type: integer
      - description: 页容
        in: query
        name: page_size
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GetPaysListOutputDto'
            type: object
      summary: 获取所有支付信息
      tags:
      - 支付接口
  /api/pay/pending:
    post:
      consumes:
      - application/json
      parameters:
      - description: 交易信息
        in: body
        name: payment_info
        required: true
        schema:
          $ref: '#/definitions/models.PaymentInfoInsertDto'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PrePaidOutputDto'
            type: object
      summary: 发起支付
      tags:
      - 支付接口
  /api/pay/status/:
    get:
      consumes:
      - application/json
      parameters:
      - description: 状态
        in: body
        name: payment_info
        required: true
        schema:
          $ref: '#/definitions/models.TradingStatusInputDto'
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 确认状态
      tags:
      - 支付接口
  /api/pay/stream:
    get:
      summary: 服务推送
      tags:
      - 支付接口
swagger: "2.0"
